create table customer_notification (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    customer_id bigint not null,
    channel varchar(30) not null,
    status varchar(30) not null,
    event_type varchar(120) not null,
    title varchar(180) not null,
    message varchar(2000) not null,
    generated_at timestamptz not null
);

create table processed_kafka_message (
    id uuid primary key,
    message_id uuid not null,
    consumer_group varchar(120) not null,
    topic varchar(180) not null,
    processed_at timestamptz not null,
    constraint uk_processed_message_consumer unique (message_id, consumer_group)
);

create index idx_customer_notification_customer on customer_notification(customer_id, generated_at desc);
create index idx_processed_kafka_message_processed_at on processed_kafka_message(processed_at desc);
