apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: banking
data:
  SPRING_PROFILES_ACTIVE: "prod"
  APP_ALLOWED_ORIGIN: "https://banking.example.com"
  JWT_ISSUER: "banking-identity"
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "PLAIN"
  IDENTITY_URL: "http://identity-service:8081"
  PROFILE_URL: "http://profile-service:8082"
  ACCOUNT_URL: "http://account-service:8083"
  PAYMENT_URL: "http://payment-service:8084"
  NOTIFICATION_URL: "http://notification-service:8085"
