apiVersion: v1
kind: Secret
metadata:
  name: banking-secret
  namespace: banking
type: Opaque
stringData:
  JWT_SECRET: "replace-with-strong-256-bit-secret"
  KAFKA_BOOTSTRAP_SERVERS: "managed-kafka-bootstrap:9092"
  KAFKA_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username='change-me' password='change-me';"
  IDENTITY_DB_URL: "jdbc:postgresql://identity-postgres:5432/identity_db"
  PROFILE_DB_URL: "jdbc:postgresql://profile-postgres:5432/profile_db"
  ACCOUNT_DB_URL: "jdbc:postgresql://account-postgres:5432/account_db"
  PAYMENT_DB_URL: "jdbc:postgresql://payment-postgres:5432/payment_db"
  NOTIFICATION_DB_URL: "jdbc:postgresql://notification-postgres:5432/notification_db"
  DB_USERNAME: "banking"
  DB_PASSWORD: "change-me"
  GOOGLE_CLIENT_ID: "change-me"
  GOOGLE_CLIENT_SECRET: "change-me"
