create table roles (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    name varchar(40) not null unique
);

create table role_permissions (
    role_id bigint not null references roles(id) on delete cascade,
    permissions varchar(80) not null,
    primary key (role_id, permissions)
);

create table user_account (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    username varchar(120) not null unique,
    email varchar(180) not null unique,
    password_hash varchar(120) not null,
    status varchar(30) not null,
    mfa_enabled boolean not null default true,
    failed_login_attempts integer not null default 0,
    last_login_at timestamptz,
    external_provider varchar(120),
    external_subject varchar(180)
);

create table user_roles (
    user_id bigint not null references user_account(id) on delete cascade,
    role_id bigint not null references roles(id) on delete restrict,
    primary key (user_id, role_id)
);

create table login_audit (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    username varchar(180) not null,
    success boolean not null,
    ip_address varchar(80),
    user_agent varchar(255),
    failure_reason varchar(500),
    occurred_at timestamptz not null
);

create index idx_login_audit_username on login_audit(username, occurred_at desc);
