create table customer_profile (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    user_id bigint not null unique,
    customer_number varchar(40) not null unique,
    first_name varchar(120) not null,
    last_name varchar(120) not null,
    email varchar(180) not null,
    phone varchar(40),
    date_of_birth date,
    nationality varchar(80),
    kyc_status varchar(30) not null,
    risk_rating varchar(30) not null,
    tax_residency_country varchar(120)
);

create table address (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    profile_id bigint not null references customer_profile(id) on delete cascade,
    type varchar(30) not null,
    line1 varchar(180) not null,
    line2 varchar(180),
    city varchar(120) not null,
    postal_code varchar(20) not null,
    country_code varchar(2) not null
);

create table customer_consent (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    profile_id bigint not null references customer_profile(id) on delete cascade,
    consent_type varchar(80) not null,
    granted boolean not null,
    captured_at timestamptz not null
);

create index idx_customer_profile_user_id on customer_profile(user_id);
create index idx_address_profile on address(profile_id);
create index idx_customer_consent_profile on customer_consent(profile_id);
