create table beneficiary (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    customer_id bigint not null,
    nickname varchar(120) not null,
    account_holder_name varchar(180) not null,
    iban varchar(40) not null,
    bic varchar(20),
    country_code varchar(2) not null,
    status varchar(30) not null
);

create table payment_instruction (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    customer_id bigint not null,
    source_account_id bigint not null,
    source_iban varchar(40) not null,
    beneficiary_id bigint not null references beneficiary(id) on delete restrict,
    type varchar(30) not null,
    status varchar(30) not null,
    amount numeric(19, 4) not null,
    currency varchar(3) not null,
    payment_reference varchar(80) not null unique,
    idempotency_key varchar(120) not null unique,
    remittance_information varchar(500) not null,
    risk_score numeric(5, 2) not null,
    scheduled_for timestamptz,
    approved_at timestamptz,
    executed_at timestamptz,
    rejection_reason varchar(500)
);

create table outbox_event (
    id uuid primary key,
    aggregate_type varchar(80) not null,
    aggregate_id varchar(80) not null,
    event_type varchar(80) not null,
    topic varchar(180) not null,
    payload text not null,
    status varchar(20) not null,
    attempts integer not null default 0,
    last_error varchar(2000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    published_at timestamptz
);

create index idx_beneficiary_customer on beneficiary(customer_id, status);
create index idx_payment_customer on payment_instruction(customer_id, created_at desc);
create index idx_outbox_event_dispatch on outbox_event(status, attempts, created_at);
