create table bank_account (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    customer_id bigint not null,
    iban varchar(40) not null unique,
    type varchar(30) not null,
    status varchar(30) not null,
    currency varchar(3) not null,
    ledger_balance numeric(19, 4) not null,
    available_balance numeric(19, 4) not null,
    daily_transfer_limit numeric(19, 4) not null
);

create table account_transaction (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    account_id bigint not null references bank_account(id) on delete cascade,
    type varchar(30) not null,
    amount numeric(19, 4) not null,
    currency varchar(3) not null,
    reference varchar(80) not null unique,
    description varchar(500) not null,
    posted_at timestamptz not null
);

create table account_hold (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    account_id bigint not null references bank_account(id) on delete cascade,
    amount numeric(19, 4) not null,
    reference varchar(80) not null,
    expires_at timestamptz not null,
    released boolean not null default false
);

create table outbox_event (
    id uuid primary key,
    aggregate_type varchar(80) not null,
    aggregate_id varchar(80) not null,
    event_type varchar(80) not null,
    topic varchar(180) not null,
    payload text not null,
    status varchar(20) not null,
    attempts integer not null default 0,
    last_error varchar(2000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    published_at timestamptz
);

create index idx_bank_account_customer on bank_account(customer_id);
create index idx_account_transaction_account_posted on account_transaction(account_id, posted_at desc);
create index idx_outbox_event_dispatch on outbox_event(status, attempts, created_at);
